import React, { useState } from 'react';
import {
  FileText,
  Brain,
  Download,
  Printer,
  Sparkles,
  Calendar,
  Layers,
  Building,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  Copy,
  Check,
  Share2,
  ShieldAlert,
  Info,
} from 'lucide-react';
import { MonitoringStation, GrapStageInfo } from '../types';
import { useLanguage } from '../context/LanguageContext';

interface ReportsViewProps {
  stations: MonitoringStation[];
  grapStage: GrapStageInfo;
}

export const ReportsView: React.FC<ReportsViewProps> = ({ stations, grapStage }) => {
  const { t } = useLanguage();
  const [reportType, setReportType] = useState('daily_briefing');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  const avgAqi = Math.round(
    stations.reduce((sum, s) => sum + s.aqi, 0) / (stations.length || 1)
  );
  const maxStation = [...stations].sort((a, b) => b.aqi - a.aqi)[0] || stations[0];

  const currentDate = new Date().toLocaleDateString('en-IN', {
    timeZone: 'Asia/Kolkata',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const defaultBriefing = `# DELHI-NCR AIR QUALITY DECISION SUPPORT & ASSESSMENT DOSSIER
**Document Ref:** SIH-AIRSHED/DELHI/EVAL-${new Date().toISOString().split('T')[0]}
**Date & Time:** ${currentDate} | 10:00 IST
**Airshed Baseline:** 10 Continuous Ambient Air Quality Monitoring (CAAQMS) Nodes
**Simulated / Active GRAP Stage:** Stage ${grapStage.roman} (${grapStage.title})
**Regional Mean AQI:** ${avgAqi} (Category: Severe/Very Poor)
**Peak Hotspot Station:** ${maxStation.name} (${maxStation.aqi} AQI | PM2.5: ${maxStation.pm25} µg/m³)

---

> [!NOTE]
> **Decision Support Disclaimer:** This technical briefing is generated by the SIH Delhi-NCR Integrated Decision Support Platform using real-time sensor streams and atmospheric dispersion models. It is prepared for academic and decision-support evaluation purposes.

---

## 1. Executive Airshed Synopsis
The Delhi-National Capital Region airshed is currently characterized by atmospheric stagnation with planetary boundary layer (PBL) mixing height compressed below **380 meters**. Stable nocturnal thermal subsidence coupled with north-westerly surface wind advection (mean 4.2 km/h) has elevated fine particulate matter (PM2.5) concentrations significantly above national ambient guidelines.

---

## 2. Chemical Speciation & PMF Source Apportionment
- **Transport & Vehicular Exhaust (42%):** Primary diesel particulate matter, elemental carbon, and NOx emissions along major arterial corridors.
- **Transboundary Agricultural Biomass (26%):** Satellite VIIRS clusters indicate active upwind stubble burning plumes traversing the Punjab-Haryana corridor.
- **Industrial Combustion & Kilns (16%):** Concentrated secondary sulfur and nitrogen aerosols across trans-Yamuna industrial zones.
- **Resuspended Road & Construction Dust (11%):** Coarse particulate fraction (PM10 > 260 µg/m³).
- **Secondary Aerosols & Domestic Waste (5%):** Local biomass and municipal refuse combustion.

---

## 3. Recommended Multi-Sectoral Intervention Matrix
1. **Vehicular Traffic Management:** Enforce strict restrictions on non-BS6 commercial heavy vehicles and promote mass transit ridership.
2. **Dust Suppression Regimes:** Deploy high-frequency mechanical sweeping and water misting along Ring Road, Outer Ring Road, and Anand Vihar corridors.
3. **Construction & Demolition Protocols:** Enforce strict wind-break barriers and wet-cutting compliance across active infrastructure projects.
4. **Institutional Advisories:** Recommend staggered working hours and remote operations to attenuate morning and evening transit exposure peaks.

---

## 4. Public Health & Community Protection Guidance
- **Respirator Advisory:** Recommend certified N95/N99 respirators for vulnerable populations during outdoor commuting.
- **Diurnal Timing:** Minimize strenuous outdoor physical activity between 05:00–09:00 IST and 20:00–23:00 IST when thermal inversion is most pronounced.
- **Indoor Air Quality:** Maintain indoor CADR air filtration and seal nocturnal ventilation gaps.

*Compiled via Delhi-NCR Air Quality & Decision Support Engine (SIH-035)*`;

  const [generatedReport, setGeneratedReport] = useState<string>(defaultBriefing);

  const handleGenerateAiReport = async () => {
    setIsGenerating(true);

    try {
      const response = await fetch('/api/generate-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          reportType,
          date: new Date().toISOString().split('T')[0],
          avgAqi,
          maxStation: { name: maxStation.name, aqi: maxStation.aqi },
          grapStage: grapStage.roman,
          fireCount: 23,
          stationsSummary: stations.reduce((acc: Record<string, number>, s) => {
            acc[s.name] = s.aqi;
            return acc;
          }, {}),
        }),
      });

      const data = await response.json();
      if (data.report) {
        setGeneratedReport(data.report);
      } else {
        setGeneratedReport(defaultBriefing);
      }
    } catch {
      setGeneratedReport(defaultBriefing);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-5 pb-8">
      {/* Header Bar */}
      <div className="bg-[#0c111e] border border-slate-800 p-5 rounded-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-black tracking-[0.25em] uppercase text-cyan-400">
              DECISION SUPPORT INTELLIGENCE
            </span>
            <span className="px-1.5 py-0.5 bg-cyan-500/20 border border-cyan-500/30 text-cyan-300 text-[9px] font-mono rounded">
              A4 PRINT / PDF READY
            </span>
          </div>
          <h1 className="text-xl sm:text-2xl font-black tracking-tight text-white uppercase mt-1">
            {t.tabReports}
          </h1>
          <p className="text-xs text-slate-400 mt-0.5 max-w-2xl">
            Automated technical briefings and multi-node assessment dossiers for regional environmental management and policy evaluation.
          </p>
        </div>

        <div className="flex items-center gap-2.5 flex-wrap">
          <button
            onClick={handleCopy}
            className="px-3 py-2 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 text-xs font-bold rounded-lg transition-colors flex items-center gap-1.5"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Text'}</span>
          </button>

          <button
            onClick={handlePrint}
            className="px-3.5 py-2 bg-white text-black hover:bg-slate-200 text-xs font-black uppercase rounded-lg transition-all flex items-center gap-1.5 shadow"
          >
            <Printer className="w-3.5 h-3.5 text-black" />
            <span>{t.exportPdf}</span>
          </button>

          <button
            onClick={handleGenerateAiReport}
            disabled={isGenerating}
            className="px-4 py-2 bg-gradient-to-r from-red-600 to-rose-600 hover:from-red-500 hover:to-rose-500 disabled:opacity-50 text-white text-xs font-black uppercase tracking-wider rounded-lg transition-all flex items-center gap-1.5 shadow-[0_0_15px_rgba(220,38,38,0.3)]"
          >
            <Sparkles className="w-3.5 h-3.5 animate-spin" style={{ animationDuration: isGenerating ? '1s' : '0s' }} />
            <span>{isGenerating ? 'Synthesizing...' : t.generateReport}</span>
          </button>
        </div>
      </div>

      {/* Report Controls & Format Selector */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
        <div className="bg-[#0f1629] border border-slate-800 p-3 rounded-xl">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1">
            Report Template
          </span>
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="w-full bg-slate-900 border border-slate-700 text-white text-xs font-bold rounded-lg px-2.5 py-1.5 focus:outline-none focus:border-cyan-400"
          >
            <option value="daily_briefing">Daily Airshed Executive Briefing</option>
            <option value="grap_audit">GRAP Stage Compliance Audit</option>
            <option value="source_apportionment">PMF Chemical Source Synthesis</option>
            <option value="inversion_meteorology">Meteorological Inversion Assessment</option>
          </select>
        </div>

        <div className="bg-[#0f1629] border border-slate-800 p-3 rounded-xl">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1">
            Airshed Status
          </span>
          <div className="text-sm font-bold text-white">
            Mean AQI: <span className="text-red-400">{avgAqi}</span> (10 Nodes)
          </div>
        </div>

        <div className="bg-[#0f1629] border border-slate-800 p-3 rounded-xl">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1">
            Peak Node Hotspot
          </span>
          <div className="text-sm font-bold text-amber-400 truncate">
            {maxStation.name} ({maxStation.aqi} AQI)
          </div>
        </div>

        <div className="bg-[#0f1629] border border-slate-800 p-3 rounded-xl">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block mb-1">
            GRAP Status
          </span>
          <div className="text-sm font-bold text-red-400">
            Stage {grapStage.roman} &bull; {grapStage.title}
          </div>
        </div>
      </div>

      {/* Printable Dossier Document Preview */}
      <div className="bg-[#0a0e19] border border-slate-800 rounded-xl p-6 sm:p-10 shadow-2xl relative">
        {/* Printable Official-Style Header */}
        <div className="border-b-2 border-slate-700 pb-5 mb-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <div className="text-[11px] font-black uppercase tracking-[0.2em] text-cyan-400">
                DELHI-NCR AIR QUALITY ASSESSMENT & POLICY SUPPORT PLATFORM
              </div>
              <h2 className="text-lg sm:text-xl font-black text-white mt-1">
                STATUTORY AIRSHED ASSESSMENT DOSSIER
              </h2>
              <div className="text-xs text-slate-400 mt-0.5">
                Scientific Monitoring & Decision Support Briefing &bull; Problem Code: SIHI035
              </div>
            </div>

            <div className="text-right sm:border-l sm:border-slate-800 sm:pl-4">
              <span className="text-[10px] font-mono text-slate-400 block">Generated On</span>
              <span className="text-xs font-bold text-white font-mono">{currentDate}</span>
              <span className="text-[9px] text-cyan-400 font-mono block mt-0.5">SHA256: 4F92A-EVAL-2024</span>
            </div>
          </div>
        </div>

        {/* Markdown Rendered Content Area */}
        <div className="prose prose-invert max-w-none text-slate-200 text-xs sm:text-sm leading-relaxed whitespace-pre-line font-sans">
          {generatedReport}
        </div>

        {/* Dossier Footer Disclaimer */}
        <div className="mt-8 pt-4 border-t border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-[10px] text-slate-400 font-mono">
          <div className="flex items-center gap-1.5">
            <Info className="w-3.5 h-3.5 text-cyan-400" />
            <span>{t.disclaimerText}</span>
          </div>
          <span>Document Ref: SIH-NCR-AIRSHED-2024</span>
        </div>
      </div>
    </div>
  );
};
